// SPDX-License-Identifier: GPL-3.0-or-later
// Every image is produced by the corresponding current-source draw-shot harness.
window.nativeScreens = [
 {id:'appearance',group:'Design & desktop',title:'Appearance',lead:'The real Appearance page.',description:'Theme families, accent selection, surface treatment, translucency and blur share one page. The material-controls frame shows the same native page scrolled further down.',source:'panel/src/capsule-settings.c · draw_appearance',fixture:'Carbon Blue, Paper and Stainless theme variants; isolated demonstration preferences.',variants:[['appearance','Carbon Blue'],['appearance-paper','Paper'],['appearance-metal','Stainless / Chrome'],['appearance-materials','Material controls']]},
 {id:'material-studio',group:'Design & desktop',title:'Material Studio',lead:'One material choice can shape the whole system.',description:'The current native Settings source exposes sixteen material worlds, six visual languages, depth, scope, motion and custom icons. Applying a material updates shared surface and control roles as well as the semantic file-icon profile. This capture is a real offscreen render of that page.',source:'panel/src/capsule-settings.c · shared/iconprofile.c',fixture:'Isolated preferences using the Iridescent Titanium demonstration profile; no user settings were changed.',variants:[['material-studio','Material Studio']]},
 {id:'wallpaper',group:'Design & desktop',title:'Wallpaper',lead:'Wallpaper has its own place.',description:'The native wallpaper picker exposes the scene collection separately from Appearance. Scenes use the shared rendering system; this is the actual page, not a web approximation.',source:'panel/src/capsule-settings.c · shared/wallpaper-scenes.c',fixture:'Isolated preferences; native scene thumbnails.',variants:[['wallpaper','Wallpaper picker']]},
 {id:'dock-settings',group:'Design & desktop',title:'Dock',lead:'More than three launch buttons.',description:'The Dock page covers placement, size, auto-hide and indicators. The native dock also tracks starting, running and minimized applications; this image shows its configuration surface.',source:'panel/src/capsule-settings.c · panel/src/capsule-panel.c',fixture:'Default isolated preferences; no running applications.',variants:[['dock-settings','Dock controls']]},
 {id:'desktop',group:'Design & desktop',title:'Desktop & menu',lead:'Files live on the desktop, too.',description:'The native panel draws desktop icons, file-kind graphics, selection and a contextual menu over its own Folded Light wallpaper. This is a desktop-layer render; the compositor, title bars and dock are not composited into this image.',source:'panel/src/capsule-panel.c · tools/draw-shot-desktop.c',fixture:'Harness-generated folders and files; native wallpaper and menu.',variants:[['desktop','Desktop context menu'],['launcher','Launcher']]},
 {id:'library',group:'Apps & games',title:'Library',lead:'A collection with a controller home.',description:'Library has category navigation, a controller page and a route back to the desktop. Compare a collection containing one fictional capsule with the empty state and controller controls. The empty state contains a confirmed misleading Install route; see status note 07.',source:'panel/src/capsule-library.c · panel/src/library-home-ui.h',fixture:'Sample Notes is a metadata-only fixture, not a runnable app. The empty-state capture has no installed capsules. Controller names and ordering are harness samples.',variants:[['library-sample','Sample collection'],['library','Empty state'],['controllers','Controllers & players']]},
 {id:'capper',group:'Apps & games',title:'Capper',lead:'Browse, review, then build a capsule.',description:'The store UI presents application categories, a cart and installation progress. The displayed package catalog is the native harness’s sample data. No package shown here has been downloaded, installed, or compatibility-tested by this website.',source:'panel/src/capsule-capper.c · tools/draw-shot-capper.c',fixture:'Built-in sample package catalog and queue; third-party names identify examples only.',variants:[['capper','Application catalog'],['capper-own','Install your own']]},
 {id:'encapsulator',group:'Apps & games',title:'Encapsulator',lead:'Import a collection with a review step.',description:'Encapsulator is a distinct mode of the native Capper program. It exposes the bulk-import queue, identified systems, firmware information and per-item review. The sample queue does not import or distribute its named contents.',source:'panel/src/capsule-capper.c · draw_bulk · tools/capsule-import',fixture:'Existing native harness bulk-queue fixture; metadata only. No game media or cover art.',variants:[['encapsulator','Bulk import review']]},
 {id:'permissions',group:'System & access',title:'App properties',lead:'An application’s access and runtime, in detail.',description:'The native Properties window has more controls than the three-switch exercise. Compare its Permissions page with How it runs, which reads configurable options from the actual Wine runtime definition.',source:'panel/src/capsule-permissions.c · tools/capsule-prefs · runtime-defs/wine-11.15-staging.json',fixture:'Fictional Sample Notes manifest requesting Documents and speakers; no payload, real signature, or runnable application.',variants:[['permissions','Permissions'],['runtime-options','How it runs']]},
 {id:'gaming',group:'Apps & games',title:'Gaming Mode',lead:'Choose how the desktop behaves during play.',description:'The actual Gaming Mode settings page exposes its current controls. Source implementation also interacts with power/idle behavior and application visibility. The image is not a performance benchmark.',source:'panel/src/capsule-settings.c · compositor/src/capsule-wm.c',fixture:'Isolated preferences; the harness may populate demonstration capsule metadata for this page.',variants:[['gaming','Gaming Mode']]},
 {id:'system-settings',group:'System & access',title:'Displays & maintenance',lead:'The machine around the applications.',description:'Displays, Storage and Updates are real Settings pages. These captures show the UI in an offscreen environment; display/hardware availability and update discovery are not evidence about a physical machine.',source:'panel/src/capsule-settings.c',fixture:'Isolated home in WSL; Storage lists the build environment’s virtual disks, Displays has no reported connectors, and Updates shows an environment without an installed-image identity. No settings or disks were changed.',variants:[['displays','Displays'],['storage','Storage'],['updates','Updates']]},
 {id:'files',group:'Everyday tools',title:'Files',lead:'A full file manager, not a folder toggle.',description:'Places and capsule storage share a sidebar. Grid and details views show the same fictional documents. The source also includes multi-selection, drag-and-drop, Trash, network locations and contextual file actions.',source:'panel/src/capsule-files.c',fixture:'Three authored demonstration documents and two empty folders in a private fixture home; sidebar mount labels come from the build environment.',variants:[['files','Grid view'],['files-details','Details view']]},
 {id:'sound',group:'Everyday tools',title:'Sound',lead:'Mixer, equalizer, routing and sound profiles.',description:'The actual Sound window has separate pages for mixer controls, equalization, routing, system sounds and keyboard sounds. The preview shows sample devices; it does not read or change your audio.',source:'panel/src/capsule-sound.c · tools/draw-shot-sound.c',fixture:'Synthetic audio devices and levels from the existing native harness.',variants:[['sound','Mixer'],['equalizer','Equalizer']]},
 {id:'media-surface',group:'Everyday tools',title:'Media Surface',lead:'Playback with an explicit boundary.',description:'The native controller owns the queue and controls while a separate libVLC worker starts with no file authority. Files grants only the exact selected path. The desktop can read title, state and progress and send a fixed set of local controls without granting the decoder broad desktop-bus access.',source:'panel/src/capsule-player.c · panel/src/capsule-media-worker.c · panel/src/capsule-panel.c',fixture:'Headless native render with invented local filenames and playback times; it does not play or include media.',variants:[['media-surface','Media Surface controller']]},
 {id:'network',group:'Everyday tools',title:'Network',lead:'Wi-Fi and Bluetooth, with dedicated pages.',description:'The native Network window includes Wi-Fi, Bluetooth, wired connections and tests. These frames show the actual interface with invented networks and devices, not nearby equipment or measured connection results.',source:'panel/src/capsule-network.c · tools/draw-shot-network.c',fixture:'Synthetic networks and Bluetooth devices; no scan or connection is made.',variants:[['network','Wi-Fi'],['bluetooth','Bluetooth']]},
 {id:'accessibility',group:'System & access',title:'Accessibility',lead:'The controls that are actually there.',description:'This is the current Accessibility page from Settings. Text size and keyboard assistance are implemented in the shared UI/compositor paths. The native page and its limits matter more than a generic accessibility promise.',source:'panel/src/capsule-settings.c · shared/uiscale.h · shared/keyassist.h',fixture:'Isolated preferences at normal text scale; no accessibility certification.',variants:[['accessibility','Accessibility controls']]},
 {id:'install',group:'System & access',title:'Guided setup',lead:'Installation includes your setup choices.',description:'The installer collects account and desktop setup before formatting. This is the real setup-page renderer with fixture values. No disk is selected, formatted, installed, or restarted by the website.',source:'panel/src/capsule-install.c · panel/src/install-profile-ui.h',fixture:'Harness-generated account details; no credentials from this computer.',variants:[['install','Account setup']]},
 {id:'logs',group:'System & access',title:'Diagnostics',lead:'A graphical route to a system report.',description:'Logs includes event views, application launch records and a report page. This frame shows the report explanation before collection. It does not contain a report from your computer.',source:'panel/src/capsule-logs.c · tools/status-report.sh',fixture:'Report landing page only; no system report collected.',variants:[['logs','Report page']]}
];
window.featureGroups = [
 {name:'Desktop & windows',source:'panel/src/capsule-panel.c; compositor/src/capsule-wm.c',items:[['Top bar & menus','Configurable menus and indicators, with machine and window actions.'],['Dock behavior','Pinning, placement, size, auto-hide, launch feedback, window state and activity indicators.'],['Desktop files','Native file icons, selection, contextual menus and Trash.'],['Window management','Focus, minimize/restore, resizing, fullscreen, saved geometry and display handling.']]},
 {name:'Design & personalization',source:'shared/theme.c; shared/wallpaper-scenes.c; shared/iconprofile.c; panel/src/capsule-settings.c',items:[['Theme families','Night, Light, Terminal, Nature, Warm, Vivid, Practical, Metal and Accessible groups in the current palette table.'],['Material Studio','Sixteen system-wide material worlds, six visual languages, depth, scope, reduced motion and custom-icon choices.'],['Semantic file icons','File type, format and state are rendered from one deterministic profile, including bounded labels and a universal fallback.'],['Wallpapers & typography','Native scene picker, font management, text scaling and shared typography roles.']]},
 {name:'Capsules, apps & games',source:'panel/src/capsule-capper.c; panel/src/capsule-library.c; tools/capsule-import; tools/capsule-controller',items:[['Capper','Application catalog, package planning, building and installation queue.'],['Encapsulator & bulk imports','Reviewed import queues, archive handling, content identification, system overrides, firmware warnings and progress.'],['Library & controller home','Collection browsing, categories, controller navigation, pairing route and player ordering.'],['Per-app configuration','Runtime settings, permissions, files, launch options, notification choices and identity information.'],['Artwork choices','Optional artwork lookup with disclosure and a standing preference; not a license to redistribute artwork.']]},
 {name:'Files & storage',source:'panel/src/capsule-files.c; panel/src/capsule-space.c; shared/dockpin.h',items:[['File management','Grid/details, search, multi-selection, copy/move, rename, Trash and undo paths.'],['Contextual actions','Action groups for supported file types, including conversion helpers; availability depends on installed tools and type.'],['Network locations','SMB, SSH/SFTP and FTP routes in Files; unsupported protocols are explicitly declined.'],['Capsule storage','Per-application storage, runtime/state accounting and removal controls.']]},
 {name:'Devices, media & connectivity',source:'panel/src/capsule-sound.c; panel/src/capsule-network.c; panel/src/capsule-player.c; panel/src/capsule-media-worker.c',items:[['Sound','Mixer, equalizer, routing, sound profiles and keyboard-sound pages.'],['Media Surface','Native queue/controller, exact-file worker grants, opt-in network playback and desktop Now Playing controls.'],['Network','Wi-Fi, Bluetooth, wired connections and diagnostic test UI.'],['Displays & controllers','Display controls plus Library navigation and player ordering; physical-device and emulator support still varies.']]},
 {name:'Access & boundaries',source:'panel/src/capsule-permissions.c; tools/capsule-run; authd/src/capsule-authd.c',items:[['Explicit grants','Folder, device and separate network choices applied by the launch path.'],['File opening & sharing','Chooser/portal paths and file grants differ from permanent whole-folder permission.'],['Identity & authorization','Capsule identity, signature/trust handling and authenticated privileged operations.'],['Account controls','Users, sign-in, security, password/keyring and startup settings.']]},
 {name:'Maintenance & recovery',source:'panel/src/capsule-install.c; panel/src/capsule-logs.c; panel/src/capsule-control.c; panel/src/capsule-settings.c',items:[['Guided OS installation','Account and preference setup, component selection and an explicit destructive-install flow.'],['Updates & reset','Signed-update tooling, update/reset pages and boot-related mechanisms; see the outstanding installation risk below.'],['Control & logs','Task/process views, performance information, termination controls and graphical diagnostics.'],['Everyday utilities','Editor, terminal, screenshot, clipboard and other native utility sources are present.']]},
 {name:'Proposals, not current screens',planned:true,source:'design/settings-organization.md; design/settings-catalog.json',items:[['New Settings organization','The nine-category navigation and applet catalog are explicitly a target design.'],['Studios & workspace proposals','Materials/Motion studios and expanded workspace, continuity, explanatory and device applets must not be advertised as shipped from these documents alone.']]}
];
